### ISSUE TITLE
docker build unable to find flowbite

### ISSUE THREAD

**Issue by bhanuvrat** [themesberg/tailwind-phoenix-starter#1]
How to reproduce
- clone the repo
- run `mix phx.gen.release --docker`
- run `docker build .`

```
#23 8.288 Rebuilding...
#23 8.290 Error: Cannot find module 'flowbite/plugin'
#23 8.290 Require stack:
#23 8.290 - /app/assets/tailwind.config.js
#23 8.290 - /snapshot/tailwindcss/lib/cli/build/plugin.js
#23 8.290 - /snapshot/tailwindcss/lib/cli/build/index.js
#23 8.290 - /snapshot/tailwindcss/lib/cli/index.js
#23 8.290 - /snapshot/tailwindcss/lib/cli.js
#23 8.290 - /snapshot/tailwindcss/standalone-cli/standalone.js
#23 8.290 1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
#23 8.290     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
#23 8.290     at Function._resolveFilename (pkg/prelude/bootstrap.js:1955:46)
#23 8.290     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
#23 8.290     at Module.require (node:internal/modules/cjs/loader:1005:19)
#23 8.290     at Module.require (pkg/prelude/bootstrap.js:1855:31)
#23 8.290     at Module.require (/snapshot/tailwindcss/standalone-cli/standalone.js:26:22)
#23 8.290     at require (node:internal/modules/cjs/helpers:102:18)
#23 8.290     at Object.<anonymous> (/app/assets/tailwind.config.js:17:5)
#23 8.290     at Module._compile (node:internal/modules/cjs/loader:1105:14)
#23 8.290     at Module._compile (pkg/prelude/bootstrap.js:1894:32) {
#23 8.290   code: 'MODULE_NOT_FOUND',
#23 8.290   requireStack: [
#23 8.290     '/app/assets/tailwind.config.js',
#23 8.290     '/snapshot/tailwindcss/lib/cli/build/plugin.js',
#23 8.290     '/snapshot/tailwindcss/lib/cli/build/index.js',
#23 8.290     '/snapshot/tailwindcss/lib/cli/index.js',
#23 8.290     '/snapshot/tailwindcss/lib/cli.js',
#23 8.290     '/snapshot/tailwindcss/standalone-cli/standalone.js'
#23 8.290   ],
#23 8.290   pkg: true
#23 8.290 }
#23 8.305
#23 8.305 12:49:08.563 [debug] Downloading esbuild from https://registry.npmjs.org/esbuild-linux-arm64/-/esbuild-linux-arm64-0.14.29.tgz
#23 9.143 ✘ [ERROR] Could not resolve "flowbite/dist/flowbite.phoenix.js"
#23 9.143
#23 9.143     js/app.js:21:7:
#23 9.143       21 │ import "flowbite/dist/flowbite.phoenix.js";
#23 9.143          ╵        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#23 9.143
#23 9.143   You can mark the path "flowbite/dist/flowbite.phoenix.js" as external to exclude it from the bundle, which will remove this error.
#23 9.143
#23 9.151 1 error
#23 9.156 ** (Mix) `mix esbuild default --minify` exited with 1
------
executor failed running [/bin/sh -c mix assets.deploy]: exit code: 1
```

**Comment by bhanuvrat** [comment]
The specification of flowbite being external needs to be mentioned in config.exs

```
config :esbuild,
  version: "0.14.29",
  default: [
    args:
      ~w(js/app.js --bundle --target=es2017 --outdir=../priv/static/assets --external:/fonts/* --external:/images/*),
    cd: Path.expand("../assets", __DIR__),
    env: %{"NODE_PATH" => Path.expand("../deps", __DIR__)}
  ]
  ```
  
  needs to be :
  ```
  config :esbuild,
  version: "0.14.29",
  default: [
    args:
      ~w(js/app.js --bundle --target=es2017 --outdir=../priv/static/assets --external:/fonts/* --external:/images/* --external:flowbite/dist/flowbite.phoenix.js),
    cd: Path.expand("../assets", __DIR__),
    env: %{"NODE_PATH" => Path.expand("../deps", __DIR__)}
  ]
  ```
